server:
  port: 3020
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eurekaProjebes/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: projestok
          uri: http://localhost:2020/projestok/
          predicates:
            - Path= /projestok/**
            #==========================
        - id: authprojebes
          uri: http://localhost:3210/authprojebes/
          predicates:
            - Path= /authprojebes/**
            #==========================
