server:
  port: 3210
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eurekaProjebes/
spring:
  application:
    name: authprojebes
  datasource:
    url: jdbc:mysql://localhost:3306/authprojebes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Murat5606
    hikari:
      connection-timeout: 3000000
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
